### ISSUE TITLE
Ordnungsamt - Bilder können nicht angezeigt werden

### ISSUE THREAD

**Issue by UnlikeMars** [SGSE-2020/Spezifikation#15]
Die Bilder für Systemübersicht und Softwarearchitektur können nicht angezeigt werden.

Link: https://sgse-2020.github.io/Spezifikation/#/./philipp_clausing/Spezifikation_Ordnungsamt?id=_31-system%c3%bcbersicht
Link: https://sgse-2020.github.io/Spezifikation/#/./philipp_clausing/Spezifikation_Ordnungsamt?id=_32-softwarearchitektur

**Comment by smartmaracl** [comment]
Fixed in latest master
