### ISSUE TITLE
Bürgerbüro - Table-of-Content-Generator von Docsify nicht unterstützt

### ISSUE THREAD

**Issue by UnlikeMars** [SGSE-2020/Spezifikation#16]
Der TOC Generator ([[_TOC_]] ) in der Entwurfsspezifikation wird von Docsify nicht unterstützt.

Link: https://sgse-2020.github.io/Spezifikation/#/./pia_schreiner/Spezifikation_Buergerbuero?id=b%c3%bcrgerb%c3%bcro-anforderungs-und-entwurfsspezifikation

**Comment by p-schreiner** [comment]
fixed
