### ISSUE TITLE
Hausarzt - Fehlende Schnittstelle

### ISSUE THREAD

**Issue by MRiechmann1** [SGSE-2020/Spezifikation#19]
Die von @AKirsch1  angeforderte Schnittstelle für Terminüberschneidungen ist nicht aufgeführt. Nochmal absprechen ob das so geplant ist und ggf. die Schnittstelle in die Spezifikation auf nehmen bzw. sie aus https://github.com/SGSE-2020/Organisation/blob/master/schnittstellen_sammlung.md streichen.

**Comment by MRiechmann1** [comment]
@TheRealMaxiM Die Schnittstelle ist bei dir auch aufgeführt

**Comment by TSMeier** [comment]
Nach Absprache mit André habe ich sie bei mir entfernt
