### ISSUE TITLE
ÖPNV- Datenmodell verwaltet Felder anderer Microservices

### ISSUE THREAD

**Issue by UnlikeMars** [SGSE-2020/Spezifikation#20]
In der Tabelle "User" werden Namen und Kontaktinformationen des Benutzers gespeichert. Diese Informationen sollten nur von dem Bürgerbüro verwaltet werden. Microservices sollten Ihre Daten möglichst gut kapseln und Datenhoheit über ihre Daten waren.

Link : https://sgse-2020.github.io/Spezifikation/#/./alexander_bergmann/Spezifikation_OPNV?id=_34-datenmodell

**Comment by abergy** [comment]
Danke für den Hinweis, ist erledigt.
