### ISSUE TITLE
Rettungsdienst - Hauptmenü Einsatz Bild wird nicht angezeigt

### ISSUE THREAD

**Issue by UnlikeMars** [SGSE-2020/Spezifikation#25]
Das Bild "Hauptmenü Einsatz" für die Graphische Benutzerschnittstelle wird nicht angezeigt.

Link:  https://sgse-2020.github.io/Spezifikation/#/./patrick_poppe/Spezifikation_Rettungsdienst?id=hauptmen%c3%bc-einsatz

**Comment by ppoppe1** [comment]
Bild wird wieder angezeigt
