### ISSUE TITLE
Rettunsgdienst - Formatierung der Modelldefinition von Schnittstellen

### ISSUE THREAD

**Issue by UnlikeMars** [SGSE-2020/Spezifikation#26]
Die Formatierung der JSON Modelldefinition sollte eingehalten werden, damit die Modelle so gut wie möglich lesbar sind. (Zusätzliche Zeilenumbrüche entfernen)

Link: https://sgse-2020.github.io/Spezifikation/#/./patrick_poppe/Spezifikation_Rettungsdienst?id=_33-schnittstellen

**Comment by ppoppe1** [comment]
Zeilenumbrüche sind raus
