### ISSUE TITLE
Krankenhaus - Überschriften

### ISSUE THREAD

**Issue by MRiechmann1** [SGSE-2020/Spezifikation#28]
Die Überschriften der Anforderungen im Detail sind nicht durch ein Leerzeichen von den '#' getrennt.
In der Systemübersicht ist GraphQL einmal mit kleinem l geschrieben.

**Comment by MRiechmann1** [comment]
Bei den Mockups auch manchmal

**Comment by UnlikeMars** [comment]
Tabelle wird ebenfalls nicht Korrekt dargestellt.

Link: https://sgse-2020.github.io/Spezifikation/#/./jendrik_mueller/Spezifikation_Krankenhaus?id=_25-anforderungen-im-detail

**Comment by jmueller19** [comment]
Hab die Überschriften und Tabelle angepasst
