### ISSUE TITLE
Krankenhaus - Teilnahme an Veranstaltungen und Krankenakte

### ISSUE THREAD

**Issue by MRiechmann1** [SGSE-2020/Spezifikation#30]
Die Schnittstelle zur Teilnahme an Veranstaltungen fehlt. Auch die Schnittstelle zum Einsehen der Krankenakte fehlte (oder ist das mit Patient abrufen gemacht?)

**Comment by jmueller19** [comment]
Die Idee mit den Veranstaltungen habe ich wieder verworfen und dementsprechend aus meiner Spezifikation entfernt. Die Krankenakte soll beim Abrufen eines Patient überliefert werden.

**Comment by MRiechmann1** [comment]
Kannst du das dann noch aus dem Schnittstellendokument in der Organisation entfernen? Und ist die Krankenakte auch in JSON format?

**Comment by jmueller19** [comment]
Habs im Schnittstellendokument angepasst. Bezüglich der Krankenakte hatte ich mich mit @TSMeier darauf geeinigt, dass diese vom Hausarzt gespeichert wird

**Comment by MRiechmann1** [comment]
Alles klar top, vielleicht dann noch in die Beschreibung einfügen bei "Abrufen des Patienten" kurz erwähnen damit jeder bescheid weiß. Dann kannst du das issue auch schließen.

**Comment by jmueller19** [comment]
Done
