### ISSUE TITLE
Krankenhaus - Formatierung der Modelldefinition von Schnittstellen

### ISSUE THREAD

**Issue by UnlikeMars** [SGSE-2020/Spezifikation#31]
Die Formatierung der JSON Modelldefinition sollte eingehalten werden, damit die Modelle so gut wie möglich zu lesen sind. (Zusätzliche Zeilenumbrüche entfernen)

Link: https://sgse-2020.github.io/Spezifikation/#/./jendrik_mueller/Spezifikation_Krankenhaus?id=_33-schnittstellen

**Comment by jmueller19** [comment]
Habe die Zeilenumbrüche entfernt
