### ISSUE TITLE
Supermarkt - Formatierung der Modelldefinition von Schnittstellen

### ISSUE THREAD

**Issue by UnlikeMars** [SGSE-2020/Spezifikation#32]
Die Formatierung der JSON Modelldefinition sollte eingehalten werden, damit die Modelle so gut wie möglich zu lesen sind. (Zusätzliche Zeilenumbrüche entfernen)

Link: https://github.com/SGSE-2020/Spezifikation/blob/andrematutat/docs/andre_matutat/spezifikation.md

**Comment by AMatutat** [comment]
Sollte gefixed sein.
