### ISSUE TITLE
Rettungsdienst - Abfrage Schnittstellen

### ISSUE THREAD

**Issue by MRiechmann1** [SGSE-2020/Spezifikation#33]
Gerade bei Schnittstellen wo man Daten anfordert wäre es gut wenn auch angegeben wird, wie die Antwort aussieht. (Einsatzbericht abfragen)

**Comment by MRiechmann1** [comment]
@PhilippCl wäre für dich bei Genehmigungen anfragen bzw. Ordnungswidrigkeiten auch relevant

**Comment by ppoppe1** [comment]
ist angepasst
