### ISSUE TITLE
Rettungsdienst - Patientendaten abrufen

### ISSUE THREAD

**Issue by MRiechmann1** [SGSE-2020/Spezifikation#34]
@jmueller19 hat die Anforderung gestellt, dass Patientendaten angeforderte werden können. Nochmal absprechen ob das so geplant ist und ggf. die Schnittstelle in die Spezifikation auf nehmen bzw. sie aus https://github.com/SGSE-2020/Organisation/blob/master/schnittstellen_sammlung.md streichen.

**Comment by ppoppe1** [comment]
@jmueller19 und ich haben uns bereits abgesprochen. Wir verstehen unter Einsatzbericht und Patientendaten beide das gleiche, haben allerdings unterschiedliche Wörter verwendet...Habe die Spezifikation in der Orga bereits angepasst
